##########################
# ROLE BINDINGS
##########################

# Specific users/groups for this cluster
groups:
  clusterSpecificGroup:
  - clusterSpecificUser1
  - clusterSpecificUser2

# Specific Rolebindings for this cluster
roleBindings:

  #######################################
  default: {}

  #######################################
  namespace1:
    admin:
      groups:
      - clusterSpecificUser1
    edit:
      serviceAccounts:
      - namespace2:serviceAccount2
    view:
      groups:
      - clusterSpecificUser2

  #######################################
  namespace2:
    admin:
      groups:
      - clusterSpecificUser2
    edit:      
      serviceAccounts:
      - namespace2/serviceAccount1
    view:
      groups:
      - clusterSpecificGroup
