##############################################################
# Default values
# Used to define common values between clusters :
# - Roles,
# - ClusterRoles,
# - Groups,
# - ClusterRoleBindings
#
# In values files specifically for a cluster :
# - Define RoleBindings
# - Extend/Override Groups
# - Extend/Override ClusterRoleBindings
##############################################################

global:
  openshift: false
  apiVersion:
    role: rbac.authorization.k8s.io/v1
    clusterRole: rbac.authorization.k8s.io/v1
    roleBinding: rbac.authorization.k8s.io/v1
    clusterRoleBinding: rbac.authorization.k8s.io/v1
    group: rbac.authorization.k8s.io/v1
    user: rbac.authorization.k8s.io/v1

######################################
# Custom Roles and ClusterRoles
######################################
roles: #{}
  default:
    myCustomRole:
    - apiGroups: [""]
      resources: ["pods", "configmaps"]
      verbs: ["get", "list"]
    - apiGroups: [""]
      resources: ["pvc"]
      verbs: ["get", "list"]

clusterRoles: #{}
  myCustomClusterRole:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]

######################################
# Groups to define in all clusters
######################################
groups:
  admins:
  - alice

  devTeam1:
  - bob
  - charlie

  qaTeam:
  - dwayne
  - elliot

######################################
# Default RoleBindings to define in all clusters
######################################
roleBindings: #{}
  # Namespace
  default: {}

  # Namespace
  development:
    # Role/ClusterRole
    admin:
      groups:
      - devTeam1
      serviceAccounts:
      - namespace1:serviceaccount
    edit:
      serviceAccounts:
      - namespace2:serviceaccount
    view:
      users:
      - dwayne

######################################
# Default ClusterRoleBindings to define in all clusters
######################################
clusterRoleBindings:

  cluster-admin:
    groups:
    - admins

  cluster-reader:
    groups:
    - devTeam1
