{{- /*  For all clusterroles defined */}}
{{- range $clusterRoleKey, $clusterRoleObject := $.Values.clusterRoleBindings }}
{{- /*  if Groups are defined */}}
{{- if $clusterRoleObject.groups }}
---
apiVersion: {{ $.Values.global.apiVersion.clusterRoleBinding }}
kind: ClusterRoleBinding
metadata:
  name: "rbac-{{ $clusterRoleKey }}-groups"
roleRef:
  name: "{{ $clusterRoleKey }}"
subjects:

{{- /*  For all Groups */}}
{{- range $entityKey, $entityValues := $clusterRoleObject }}
{{- range $entityValues }}
- kind: Group
  name: {{ . | quote }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}