{{- /*  For all clusterroles defined */}}
{{- range $clusterRoleKey, $clusterRoleObject := $.Values.clusterRoleBindings }}
{{- /*  if ServiceAccounts are defined */}}
{{- if $clusterRoleObject.serviceAccounts }}
---
apiVersion: {{ $.Values.global.apiVersion.clusterRoleBinding }}
kind: ClusterRoleBinding
metadata:
  name: "rbac-{{ $clusterRoleKey }}-sa"
roleRef:
  name: "{{ $clusterRoleKey }}"
subjects:

{{- /*  For all ServiceAccount */}}
{{- range $entityKey, $entityValues := $clusterRoleObject }}
{{- range $entityValues }}
- kind: ServiceAccount
  namespace: {{ (split "/" .)._0 | quote }}
  name: {{ (split "/" .)._1 | quote }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}