{{- /*  For all groups defined */}}
{{- range $groupKey, $groupObject := $.Values.groups }}
---
apiVersion: {{ $.Values.global.apiVersion.group }}
kind: Group
metadata:
  name: {{ $groupKey | quote }}
users:
{{- range $groupObject }}
- {{ . | quote }}
{{- end }}

{{- end }}